# Generated by Django 3.2.4 on 2021-12-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('quantity', 'quantity'), ('quality', 'quality')], max_length=100),
        ),
    ]
